# NEXTERadar config

# 配置文件

our: "red" # 我方颜色，用于确定标定数据
serial_path: "/dev/ttyUSB0" # 串口，没有串口却想看串口数据可以在main函数创建写线程调用方法 serial.debugWrite()

robot: # 设置机器人基本信息
  middle_robot_height: 0.4 # 此处设置的机器人平均高度一半，用于计算yolo框框中心到地面距离
  clearDelayTime: 1 # 目前没用

source: # 源选择，camera 特指海康
  #type: "img"
#  type: "video"
  type: "camera"
  #type: "camera_usb"
  video_L_path: "../lib/video/Left.avi"
  video_R_path: "../lib/video/Right.avi"
  map_path: "../lib/img/map2024.png"
  usb_camera_L_path: 0
  usb_camera_R_path: 0

net: # 神经网络设置
  device: 0 # 显卡设备编号
  onnx_path: "../lib/model/NERadarYM_0425_FP16.onnx" # 模型位置
  trt_path: "../lib/model/NERadarYM_0425_FP16.trt" # trt位置，与上一个应为同名同目录
  input_h: 1280 # 模型长宽
  input_w: 1280
  conf_threshold: 0.4 # 置信度阈值，yolo8只有一个置信度
  nms_threshold: 0.3 # nms 非极大值抑制阈值
  batch_size: 1 # 不要改，千万的
  num_class: 14 # 类别数量，按照实际修改

data:
  map_x_max: 28 # 场地x/y 长宽 除非DJI场地大改
  map_y_max: 15
  map_data_path: ../lib/data/mapData2024.CSV # 地图数据，详细见readme

  #2023 老的 -> 标定数据，也可以使用自己喜欢的，但是务必要与下方标定点数相同
#  demarcate_red_points: #必须与下面gui标定数量相等 自己是红方
#    0:
#      x: 9.073673364
#      y: 6.635160681
#      z: 0.0
#    1:
#      x: 9.088098918
#      y: 9.484877127
#      z: 0.0
#    2:
#      x: 10.44410098
#      y: 7.103024575
#      z: 0.6
#    3:
#      x: 10.42967543
#      y: 9.045368809
#      z: 0.6
#
#  demarcate_blue_points: #必须与下面gui标定数量相等 自己是蓝方
#    0:
#      x: 18.92632664
#      y: 8.364839319
#      z: 0.0
#    1:
#      x: 18.91190108
#      y: 5.515122873
#      z: 0.0
#    2:
#      x: 17.55589902
#      y: 7.896975425
#      z: 0.6
#    3:
#      x: 17.57032457
#      y: 5.95463138
#      z: 0.6

# 老的，不行换
#  demarcate_red_points: #必须与下面gui标定数量相等
#    0:
#      x: 8.871579
#      y: 6.806482
#      z: 0.0
#    1:
#      x: 8.856842
#      y: 9.223070
#      z: 0.0
#    2:
#      x: 17.138948
#      y: 3.274547
#      z: 0.6
#    3:
#      x: 18.966316
#      y: 8.136320
#      z: 0.6
#
#  demarcate_blue_points: #必须与下面gui标定数量相等
#    0:
#      x: 19.157894
#      y: 8.193518
#      z: 0.0
#    1:
#      x: 19.157894
#      y: 5.748332
#      z: 0.0
#    2:
#      x: 10.890542
#      y: 11.696855
#      z: 0.6
#    3:
#      x: 9.077895
#      y: 6.835081
#      z: 0.6


# 2024 1
  demarcate_red_points: #必须与下面gui标定数量相等
    0:
      x: 8.871579
      y: 6.806482
      z: 0.0
    1:
      x: 8.856842
      y: 9.223070
      z: 0.0
    2:
      x: 17.138948
      y: 3.274547
      z: 0.6
    3:
      x: 18.966316
      y: 8.136320
      z: 0.6

  demarcate_blue_points: #必须与下面gui标定数量相等
    0:
      x: 19.157894
      y: 8.193518
      z: 0.0
    1:
      x: 19.157894
      y: 5.748332
      z: 0.0
    2:
      x: 10.890542
      y: 11.696855
      z: 0.6
    3:
      x: 9.077895
      y: 6.835081
      z: 0.6

#  demarcate_red_points: #必须与下面gui标定数量相等
#    0:
#      x: 8.429474
#      y: 7.249762
#      z: 0.0
#    1:
#      x: 8.444211
#      y: 9.637760
#      z: 0.0
#    2:
#      x: 10.021053
#      y: 7.693041
#      z: 0.6
#    3:
#      x: 11.627368
#      y: 11.382269
#      z: 0.6
#
#  demarcate_blue_points: #必须与下面gui标定数量相等
#    0:
#      x: 18.745263
#      y: 8.622498
#      z: 0.0
#    1:
#      x: 18.745263
#      y: 6.205910
#      z: 0.0
#    2:
#      x: 17.153684
#      y: 8.122021
#      z: 0.6
#    3:
#      x: 15.562105
#      y: 4.475691
#      z: 0.6

gui:
  map: "lib/gui/map2023.jpg" # 这个没用
  demarcate_point_num: 4 # 标定点数，与上面标定点数量相同

class_name: # 类别名，debug界面显示的那个
  0: "ignore"
  1: "car"
  2: "R1"
  3: "R2"
  4: "R3"
  5: "R4"
  6: "R5"
  7: "R7"
  8: "B1"
  9: "B2"
  10: "B3"
  11: "B4"
  12: "B5"
  13: "B7"

set_car_armour: # 识别编号，务必于串口协议的机器人编号一致 0 代表 car  -1 代表不识别
  0: -1
  1: 0
  2: 1
  3: 2
  4: 3
  5: 4
  6: 5
  7: 7
  8: 101
  9: 102
  10: 103
  11: 104
  12: 105
  13: 107

stereo_camera_data:
  T:
    0: -779.3863636
    1: -14.14784867
    2: -102.281307

  R:
    0: 0.987357478
    1: -0.024753668
    2: -0.156564575
    3: 0.026593433
    4: 0.999599592
    5: 0.009666739
    6: 0.156262598
    7: -0.013708117
    8: 0.987620417